///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginDetail {
  String? id;
  String? roleId;
  String? email;

  LoginDetail({
    this.id,
    this.roleId,
    this.email,
  });
  LoginDetail.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    roleId = json['role_id']?.toString();
    email = json['email']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['role_id'] = roleId;
    data['email'] = email;
    return data;
  }
}

class Login {
  bool? status;
  LoginDetail? detail;
  String? message;

  Login({
    this.status,
    this.detail,
    this.message,
  });
  Login.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    detail =
        (json['detail'] != null) ? LoginDetail.fromJson(json['detail']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (detail != null) {
      data['detail'] = detail!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
